# Generated by Django 3.2.9 on 2021-12-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
